       modified:   logs.txt

no changes added to commit (use "git add" and/or "git commit -a")
Traceback (most recent call last):
  File "C:\Users\Oliwier Kania\Desktop\Moje Pliki\Nauka\Code\Python\ARTICLES\articleCheckerV3\gitManager.py", line 53, in <module>
    finisher()
  File "C:\Users\Oliwier Kania\Desktop\Moje Pliki\Nauka\Code\Python\ARTICLES\articleCheckerV3\gitManager.py", line 22, in finisher
    repo.git.push()
  File "C:\Users\Oliwier Kania\AppData\Local\Programs\Python\Python39\lib\site-packages\git\cmd.py", line 585, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Users\Oliwier Kania\AppData\Local\Programs\Python\Python39\lib\site-packages\git\cmd.py", line 1124, in _call_process
    return self.execute(call, **exec_kwargs)
  File "C:\Users\Oliwier Kania\AppData\Local\Programs\Python\Python39\lib\site-packages\git\cmd.py", line 928, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To https://github.com/oliwkan091/articleCheckerV3.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/oliwkan091/articleCheckerV3.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
